version: '3'
services:
  go:
    image: 'golang:1.17-alpine3.14'
    volumes:
      - ./src:/golang
    ports:
      - "8080:8080"
    working_dir: /golang
    tty: true
  mysql:
    image: mysql:8.0
    env_file: 
      - .env
    volumes:
      - ./mysql/data/:/docker-entrypoint-initdb.d
